# Importing NumPy

In [4]:
# first to import numpy as np for numpy array operations
import numpy as np


# Creating Array

In [6]:
# 1D Array
a = np.array([1, 2, 3])

# 2D Array
b = np.array([[1, 2], [3, 4]])

# 3D Array
c = np.array([[[1], [2]], [[3], [4]]])

print(a)
print(b)
print(c)

[1 2 3]
[[1 2]
 [3 4]]
[[[1]
  [2]]

 [[3]
  [4]]]


# Checking Array Properties

In [7]:
a.shape        # Shape of array
a.ndim         # Number of dimensions
a.dtype        # Data type
a.size         # Total number of elements
a.itemsize     # Size (in bytes) of each element
a.nbytes       # Total bytes used


12

# Initial Placeholders 

In [10]:
>>> np.zeros((3,4)) #Create an array of zeros
>>> np.ones((2,3,4),dtype=np.int16) #Create an array of ones
>>> d = np.arange(10,25,5)#Create an array of evenly spaced values (step value)
>>> np.linspace(0,2,9) #Create an array of evenlyspaced values (number of samples)
>>> e = np.full((2,2),7)#Create a constant array
>>> f = np.eye(2) #Create a 2X2 identity matrix
>>> np.random.random((2,2)) #Create an array with random values
>>> np.empty((3,2)) #Create an empty array


array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

# Creating Array With Zeros


In [24]:
a=ar.zeros((2,3))
print(a)
print()
b=ar.zeros((8,9))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Creating Array With Ones

In [25]:
a=ar.ones((3,4),dtype=int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# Reshape and Resize

In [11]:
arr = np.arange(6)       # [0 1 2 3 4 5]
arr.reshape(2, 3)        # (2 rows, 3 columns)
arr.flatten()            # Flatten to 1D
arr.resize((3, 2))       # Resizes in-place


# np.arange()
Creates a 1D array with values from 0 to 5.

In [12]:
import numpy as np

arr = np.arange(6)
print("Original array:", arr)
# Output: [0 1 2 3 4 5]


Original array: [0 1 2 3 4 5]


# arr.reshape()
Reshapes the array into 2 rows and 3 columns (returns a new reshaped array).

In [13]:
arr = np.arange(6)
arr.resize((3, 2))  # In-place
print("Resized in-place to (3, 2):\n", arr)


Resized in-place to (3, 2):
 [[0 1]
 [2 3]
 [4 5]]


# arr.resize((3, 2))
Resizes the original array in-place to 3 rows and 2 columns. This modifies arr directly.

In [16]:
arr = np.arange(6)
arr.resize((3, 2))  # In-place
print("Resized in-place to (3, 2):\n", arr)



Resized in-place to (3, 2):
 [[0 1]
 [2 3]
 [4 5]]


# Indexing and Slicing

In [17]:
# Indexing
arr = np.array([10, 20, 30, 40, 50])
print("Element at index 2:", arr[2])

Element at index 2: 30


In [19]:
# Slicing
print("Elements from index 1 to 3:", arr[1:4])
# Output: [20 30 40]


Elements from index 1 to 3: [20 30 40]


# Array Math

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c=a + b       # Element-wise addition
d=a * b       # Element-wise multiplication
e=a / b       # Division
f=a ** 2      # Power

# Simple OPerations
print(c) 
print(d) 
print(e) 
print(f) 

# np operations
np.add(a, b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


array([5, 7, 9])

In [30]:
np.multiply(a, b) # Multiply a and b


array([ 4, 10, 18])

In [31]:
np.exp(a)       # Exponential


array([ 2.71828183,  7.3890561 , 20.08553692])

In [33]:
 np.sqrt(a)      # Square root

array([1.        , 1.41421356, 1.73205081])

# Aggregate Functions

In [35]:
# sum functions
arr = np.array([[1, 2, 3], [4, 5, 6]])

np.sum(arr)



21

In [36]:
np.mean(arr) # mean of array


3.5

In [39]:
# minimum element in array
np.min(arr)



1

In [40]:
# find max element in array
np.max(arr)


6

# Boolean Masking & Filtering

In [41]:
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
a[mask]            


array([4, 5])

# Broadcasting

In [42]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

a + b   # Broadcasting b across rows


array([[11, 22, 33],
       [14, 25, 36]])

# Random in NumPy

In [43]:
np.random.seed(0)
np.random.rand(2, 3)           # Uniform [0, 1)
np.random.randn(2, 3)          # Standard normal
np.random.randint(0, 10, size=(2, 3))  # Random integers

np.random.shuffle(arr)         # Shuffle array in-place


In [44]:
import numpy as np

np.random.seed(0)
rand_uniform = np.random.rand(2, 3)
print("Random uniform [0, 1):\n", rand_uniform)


Random uniform [0, 1):
 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


# concatenating

In [29]:
a=ar.arange(1,13).reshape(3,4)
b=ar.arange(13,25).reshape(3,4)
s=ar.concatenate((a,b),axis=1)
s

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

# Converting 1D to 2D and 3D

In [29]:
a=ar.arange(1,7)
print(a.shape)
print()
print(a)
print()
print(a[ar.newaxis,:].shape)
print()
print(a[ar.newaxis,:])
s=a[ar.newaxis,:]
s[ar.newaxis,:]

(6,)

[1 2 3 4 5 6]

(1, 6)

[[1 2 3 4 5 6]]


array([[[1, 2, 3, 4, 5, 6]]])

### Expanding dimention

In [32]:
np.expand_dims(a,axis=0).shape

(1, 6)

# Non Zero

In [31]:
a = ar.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
ar.nonzero(a)
print(a[ar.nonzero(a)])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# converting array into tuple

In [32]:
a=ar.arange(1,4)
b=ar.arange(5,8)
print(a)
print()
print(b)
print()
c=list(zip(a,b))
for i in c:
    print(i)

[1 2 3]

[5 6 7]

(1, 5)
(2, 6)
(3, 7)


# Stacking

In [33]:
a=ar.arange(1,13).reshape(3,4)
b=ar.arange(13,25).reshape(3,4)
print(ar.vstack((a,b)))
print()
print(ar.hstack((a,b)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


# Sum

In [35]:
a=ar.arange(1,13)
print(ar.sum(a))
print()
b=ar.arange(13,25)
ar.sum([a,b])


78



300

# Unique

In [36]:
a=ar.array([1,2,3,2,1,4,2,5,35,33,5,22,3,1,43])
print(ar.unique(a,return_index=True))

(array([ 1,  2,  3,  4,  5, 22, 33, 35, 43]), array([ 0,  1,  2,  5,  7, 11,  9,  8, 14], dtype=int64))


# Reversing

In [37]:
a=ar.arange(1,14)
print(ar.flip(a))
print()
b=ar.arange(1,25).reshape(4,6)
print(b)
print()
print(ar.flip(b))
print(b.shape)
c=b[ar.newaxis,:]
print()
print(c)
ar.flip(c)

[13 12 11 10  9  8  7  6  5  4  3  2  1]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]
(4, 6)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


array([[[24, 23, 22, 21, 20, 19],
        [18, 17, 16, 15, 14, 13],
        [12, 11, 10,  9,  8,  7],
        [ 6,  5,  4,  3,  2,  1]]])

# Tranposing

In [38]:
a=ar.arange(12).reshape(3,4)
print(a)
print()
print(a.T)
a=ar.arange(18).reshape(2,3,3)
print()
print(a)
print()
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

[[[ 0  9]
  [ 3 12]
  [ 6 15]]

 [[ 1 10]
  [ 4 13]
  [ 7 16]]

 [[ 2 11]
  [ 5 14]
  [ 8 17]]]


In [39]:
ar.flip(c[0,1])


array([12, 11, 10,  9,  8,  7])

# Random

In [46]:
print(ar.eye(5))



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [47]:
x = ar.arange(5)
row=x[ar.newaxis,:]
col=x[:,ar.newaxis]
print(row+col)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [44]:
x = ar.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
row=ar.array([[1,1],[3,3]])
col=ar.array([[0,2],[0,2]])
x[row,col]

array([[ 3,  5],
       [ 9, 11]])

In [45]:
x = ar.arange(35).reshape(5, 7)
b=x>20
b[:,5]

array([False, False, False,  True,  True])

In [46]:
x = ar.array([[0, 1], [1, 1], [2, 2]])
x.sum(-1)

array([1, 2, 4])

In [47]:
x = ar.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
x[x.sum(-1) % 2 == 0]


array([[ 3,  4,  5],
       [ 9, 10, 11]])

# Empty array

In [49]:
a=ar.empty((3,4))
a

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313,
        1.69759663e-313],
       [2.12199579e-313, 2.54639495e-313, 2.97079411e-313,
        3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313,
        5.09278990e-313]])

### where

In [35]:
a=np.arange(1,50)
np.where(a>45)

(array([45, 46, 47, 48], dtype=int64),)

In [36]:
replace_0=np.where(a>47,0,a)
replace_0


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,  0,  0])

In [37]:
replace_even_0=np.where(a%2==0,0,a)
replace_even_0

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0, 21,  0, 23,  0, 25,  0, 27,  0, 29,  0, 31,  0, 33,  0,
       35,  0, 37,  0, 39,  0, 41,  0, 43,  0, 45,  0, 47,  0, 49])

In [40]:
np.percentile(a,100)

49.0

In [42]:
a=np.array([1,2,3,4,1,5,2,6,3,6,2,51,3,5,1,512,5,2,4,2,5,7,8,3,1,3,21,1,1,3,1,4,1,4,1,3,1,2,5,2,5,63,5,3,6,33,655,4,4,4,3,3,3,3,35,5,5,6,1,7,7,8,1,8,7,5,4,3,3])
np.histogram(a,bins=[0,50,1000])

(array([65,  4], dtype=int64), array([   0,   50, 1000]))

# Dimensional indexing tools

In [44]:
x=ar.arange(36).reshape(2,3,6)
print(x)
print(x[0,Ellipsis])
print()
print(x[:, :,0])
print()
print(x[:, ar.newaxis, :,:])
print()
print(x[:, ar.newaxis, :,:].shape)
print()
print(x[ar.newaxis,:, :,:])
print()
print(x[ar.newaxis,:,:].shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

[[ 0  6 12]
 [18 24 30]]

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]]]


 [[[18 19 20 21 22 23]
   [24 25 26 27 28 29]
   [30 31 32 33 34 35]]]]

(2, 1, 3, 6)

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]]

  [[18 19 20 21 22 23]
   [24 25 26 27 28 29]
   [30 31 32 33 34 35]]]]

(1, 2, 3, 6)


In [ ]:
x=ar.arange(5)
print(x[:,ar.newaxis]+x[ar.newaxis,:])
print()


# Advance indexing

In [48]:
x=ar.arange(25).reshape(5,5)
print(x)
print()
row=ar.array([[1,1],[3,3]])
col=ar.array([[1,-1],[1,-1]])
print(x[row,col])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 6  9]
 [16 19]]
